#!/bin/sh

. /lib/functions.sh

STATUS=$1
IFACE=$2

# callback called by config_load tunneldigger
config_cb() {
	local cfg="$CONFIG_SECTION"
  config_get configname "$cfg" TYPE

  case "$configname" in
    broker)
      config_get limit_bw_up "$cfg" limit_bw_up

      tc qdisc del dev $IFACE root
      tc qdisc add dev $IFACE root handle 1: htb default 1
      tc class add dev $IFACE parent 1: classid 1:1 htb rate $limit_bw_up ceil $limit_bw_up

    ;;
  esac
}


# TODO don't use ifconfig (it's deprecated)

case "$STATUS" in
  session.up)
    echo "Received 'session.up' for interface ${IFACE}"

    batctl if add $IFACE
    ifconfig $IFACE up
    config_load tunneldigger 

    ;;
  session.down)
    echo "Received 'session.down' for interface ${IFACE}"

    batctl if del $IFACE

    ;;
esac

